apiVersion: game.example.com/v1alpha1
kind: GSDeployment
metadata:
  labels:
    app.kubernetes.io/name: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: gsdeployment-sample
spec:
  # TODO(user): Add fields here
